edu:
  nyu:
    yz518:
      minesweeper-ui:
        row-count: 16
        col-count: 16
        mine-count: 5
        time-limit: 1000
      svc:
        url: http://localhost:8081/
spring:
  main:
    web-application-type: none